import { jsPDF } from 'jspdf';

/**
 * Export translation history to PDF
 * @param {Array} history - Array of translation records
 * @returns {void}
 */
export const exportToPDF = (history) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('EchoVerse Translation History', 20, 20);

  // Subtitle
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Exported on: ${new Date().toLocaleString()}`, 20, 30);

  // Horizontal line
  doc.setLineWidth(0.5);
  doc.line(20, 35, 190, 35);

  // History entries
  doc.setFontSize(12);
  let y = 45;

  if (history.length === 0) {
    doc.text('No translations recorded.', 20, y);
  } else {
    history.forEach((entry, index) => {
      // Check if we need a new page
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      // Entry number and timestamp
      doc.setFont('helvetica', 'bold');
      doc.text(`#${index + 1}`, 20, y);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text(new Date(entry.timestamp).toLocaleString(), 35, y);

      // Translation text
      doc.setFontSize(12);
      y += 7;
      const textLines = doc.splitTextToSize(entry.text || '(empty)', 170);
      doc.text(textLines, 20, y);
      y += textLines.length * 7 + 10;
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${pageCount} - Generated by EchoVerse`,
      105,
      290,
      { align: 'center' }
    );
  }

  // Download
  doc.save('echoverse-history.pdf');
};

/**
 * Export translation history to text file
 * @param {Array} history - Array of translation records
 * @returns {void}
 */
export const exportToText = (history) => {
  let content = 'EchoVerse Translation History\n';
  content += `Exported on: ${new Date().toLocaleString()}\n`;
  content += '='.repeat(50) + '\n\n';

  if (history.length === 0) {
    content += 'No translations recorded.\n';
  } else {
    history.forEach((entry, index) => {
      content += `#${index + 1} - ${new Date(entry.timestamp).toLocaleString()}\n`;
      content += `${entry.text || '(empty)'}\n`;
      content += '-'.repeat(30) + '\n\n';
    });
  }

  content += '\nGenerated by EchoVerse - Sign Language Translator';

  // Create and download file
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'echoverse-history.txt';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
